sudo: false
language: php

php:
  - 5.6

before_install:
  - composer selfupdate
  - phpenv config-rm xdebug.ini

install:
  # Load composer dependencies.
  - composer validate --no-check-all --ansi
  - composer install
  - git diff --name-only $TRAVIS_COMMIT_RANGE > changed_files.txt

script:
  # Run for each changed file the code sniffer.
  - ./vendor/bin/phpcs --file-list=changed_files.txt
